---
title: "Project:  Understanding disruptive powers of IoT in the energy sector (Power)"
---

IoT is expected to play a major part in the ongoing transition of energy systems. With the possibility of new actors, tariffs, appliances and relationships, IoT could disrupt the energy market – whether for the better or worse. The notion of “disruption” should not be taken for granted – IoT’s success relies on software developers’ assumptions as well as regulatory requirements with regards security, privacy and data sharing. What arrangements are “good enough” to make IoT work? What are the social implications of these arrangements? What are the regulatory gaps resulting from development of IoT? How do we facilitate development of responsible innovation where IoT is aligned with policy goals of decarbonisation, affordability and security?


Previous research on IoT in energy focuses on appliances, consumers and emerging technologies. So far, there has been little focus on IoT in energy organisations and interactions between them. Without critical social science research on the disruptive powers of IoT to security and privacy of energy markets, there is a risk that energy innovation will not be aligned with public interest. The researchers will deliver reports on the future of current policies like Network and Information Systems Security Regulation and proposed regulations to consumer IoT security, and will engage with stakeholders in the field to inform current initiatives.

<span style="color: red; font-style: italic;"> Outputs: COMING SOON!</span>
